replace:
  sound: null
  by:
  - '*#!'
  - '...'
  - :)
warn:
  cancel: false
  sound: BLOCK_ANVIL_LAND
  messages:
  - '&lDon''t say that'
  - '&o&8Nope'
  - <curse> <player> <curse> <player> <curse> <player>
slap:
  cancel: false
  sound: BLOCK_GLASS_BREAK
  damages: 2
kick:
  cancel: true
  times: 1
  messages:
  - Bow to death, <player>