replace:
  delay: 3
  sound: null
  by:
  - '*#!'
  - '...'
  - :)
warn:
  cancel: false
  delay: 3
  sound: BLOCK_ANVIL_LAND
  messages:
  - '&lDon''t say that'
  - '&o&8Nope'
  - <curse> <player> <curse> <player> <curse> <player>
slap:
  cancel: false
  delay: 10 # Should be minimum 10
  sound: BLOCK_GLASS_BREAK
  damages: 2
kick:
  cancel: true
  delay: 0 # For the sake of consistency
  times: 1
  messages:
  - Bow to death, <player>